name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mawenv: [ staging, prod ]

    steps:
    - uses: actions/checkout@v4

    - name: validate nginx config
      run: ./validate-config.sh ${{ matrix.mawenv }}
